spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
  main:
    allow-bean-definition-overriding: true

fior:
  auth:
    google-client-id: ${GOOGLE_CLIENT_ID}
  token:
    signing-key: ${SECRET}
    durations:
      access-token: 28800
      reset-token: 3600
      confirm-token: 3600
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    sender: "no-reply@fior.app"
    templates:
      email-confirmation: "d-9bbb6721ed274fcbae3b6d369db3074b"
      forgot-password: "d-f13c22e0126d4909a3cdb6d5af14ac14"
